import { useState, useEffect, useRef } from 'react';
import { Mail, MessageCircle, CheckCircle2, XCircle, RefreshCw, LogOut, Phone, User } from 'lucide-react';
import { QRCodeSVG } from 'qrcode.react';
import { getApiUrl } from '../config';

export function LinkAccountsScreen() {
  const [emailConnected, setEmailConnected] = useState(false);
  const [whatsappConnected, setWhatsappConnected] = useState(false);
  const [smtpHost, setSmtpHost] = useState('');
  const [smtpPort, setSmtpPort] = useState('');
  const [smtpUsername, setSmtpUsername] = useState('');
  const [smtpPassword, setSmtpPassword] = useState('');
  const [qrCodeData, setQrCodeData] = useState(null);
  const [qrCodeLoading, setQrCodeLoading] = useState(false);
  const [qrCodeExpired, setQrCodeExpired] = useState(false);
  const [connectionDetails, setConnectionDetails] = useState(null);
  const hasAutoGeneratedRef = useRef(false);

  // Load SMTP configuration on mount
  useEffect(() => {
    const loadSmtpConfig = async () => {
      try {
        const token = localStorage.getItem('token');
        const response = await fetch(getApiUrl('api/smtp/config'), {
          headers: {
            'Authorization': `Bearer ${token}`
          }
        });

        if (response.ok) {
          const data = await response.json();
          if (data.connected && data.config) {
            setEmailConnected(true);
            setSmtpHost(data.config.host || '');
            setSmtpPort(data.config.port?.toString() || '');
            setSmtpUsername(data.config.username || '');
            // Don't load password for security
          }
        }
      } catch (error) {
        console.error('Error loading SMTP config:', error);
      }
    };

    loadSmtpConfig();
  }, []);

  const handleEmailConnect = async () => {
    if (!smtpHost || !smtpPort || !smtpUsername || !smtpPassword) {
      alert('Please fill in all SMTP fields');
      return;
    }

    try {
      const token = localStorage.getItem('token');
      const response = await fetch(getApiUrl('api/smtp/config'), {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`
        },
        body: JSON.stringify({
          host: smtpHost,
          port: smtpPort,
          username: smtpUsername,
          password: smtpPassword,
          secure: smtpPort === '465' || smtpPort === '587' // Common secure ports
        })
      });

      if (response.ok) {
        const data = await response.json();
        setEmailConnected(true);
        alert(data.message || 'Email SMTP configured successfully!');
      } else {
        const errorData = await response.json();
        alert(errorData.error || 'Failed to save SMTP configuration');
      }
    } catch (error) {
      console.error('Error saving SMTP config:', error);
      alert('Failed to save SMTP configuration. Please try again.');
    }
  };

  const handleEmailDisconnect = async () => {
    if (!confirm('Are you sure you want to disconnect and delete SMTP configuration?')) {
      return;
    }

    try {
      const token = localStorage.getItem('token');
      const response = await fetch(getApiUrl('api/smtp/config'), {
        method: 'DELETE',
        headers: {
          'Authorization': `Bearer ${token}`
        }
      });

      if (response.ok) {
        setEmailConnected(false);
        setSmtpHost('');
        setSmtpPort('');
        setSmtpUsername('');
        setSmtpPassword('');
        alert('SMTP configuration deleted successfully');
      } else {
        const errorData = await response.json();
        alert(errorData.error || 'Failed to delete SMTP configuration');
      }
    } catch (error) {
      console.error('Error deleting SMTP config:', error);
      alert('Failed to delete SMTP configuration. Please try again.');
    }
  };

  const handleGoogleAuth = () => {
    alert('Redirecting to Google OAuth...');
    setTimeout(() => {
      setEmailConnected(true);
    }, 1000);
  };

  const handleOutlookAuth = () => {
    alert('Redirecting to Microsoft OAuth...');
    setTimeout(() => {
      setEmailConnected(true);
    }, 1000);
  };

  const generateQRCode = async () => {
    setQrCodeLoading(true);
    setQrCodeExpired(false);
    
    try {
      const token = localStorage.getItem('token');
      const response = await fetch(getApiUrl('api/whatsapp/qrcode'), {
        headers: {
          'Authorization': `Bearer ${token}`
        }
      });

      if (!response.ok) {
        throw new Error('Failed to generate QR code');
      }

      const data = await response.json();
      
      // Check if already connected
      if (data.connected) {
        setWhatsappConnected(true);
        setQrCodeData(null);
        return;
      }
      
      // Set QR code data
      setQrCodeData(data);
      
      // Set expiration timer if expiresIn is provided
      if (data.expiresIn) {
        setTimeout(() => {
          setQrCodeExpired(true);
        }, data.expiresIn * 1000);
      }
    } catch (error) {
      console.error('QR Code generation error:', error);
      alert('Failed to generate QR code. Please try again.');
    } finally {
      setQrCodeLoading(false);
    }
  };

  const handleWhatsAppConnect = () => {
    generateQRCode();
  };

  // Check WhatsApp connection status on mount and automatically generate QR if not connected
  useEffect(() => {
    let isMounted = true;
    
    const checkStatusAndGenerateQR = async () => {
      try {
        const token = localStorage.getItem('token');
        const statusResponse = await fetch(getApiUrl('api/whatsapp/status'), {
          headers: {
            'Authorization': `Bearer ${token}`
          }
        });

        if (!statusResponse.ok || !isMounted) return;

        const statusData = await statusResponse.json();
        
        if (isMounted) {
          setWhatsappConnected(statusData.connected);
          
          if (statusData.connected) {
            // Show connection details if connected
            setConnectionDetails(statusData);
            setQrCodeData(null); // Clear QR code when connected
            hasAutoGeneratedRef.current = false; // Reset flag
          } else {
            // If not connected, automatically generate QR code (only once on mount)
            setConnectionDetails(null);
            if (!hasAutoGeneratedRef.current) {
              hasAutoGeneratedRef.current = true;
              generateQRCode();
            }
          }
        }
      } catch (error) {
        console.error('Status check error:', error);
      }
    };

    // Initial check and QR generation
    checkStatusAndGenerateQR();
    
    // Check status every 5 seconds (but don't auto-generate QR on subsequent checks)
    const interval = setInterval(async () => {
      if (!isMounted) return;
      
      try {
        const token = localStorage.getItem('token');
        const response = await fetch(getApiUrl('api/whatsapp/status'), {
          headers: {
            'Authorization': `Bearer ${token}`
          }
        });

        if (response.ok && isMounted) {
          const data = await response.json();
          setWhatsappConnected(data.connected);
          if (data.connected) {
            setConnectionDetails(data);
            setQrCodeData(null);
            hasAutoGeneratedRef.current = false; // Reset flag when connected
          } else {
            setConnectionDetails(null);
          }
        }
      } catch (error) {
        console.error('Status check error:', error);
      }
    }, 5000);
    
    return () => {
      isMounted = false;
      clearInterval(interval);
    };
  }, []);

  const handleWhatsAppDisconnect = async () => {
    if (!confirm('Are you sure you want to disconnect WhatsApp?')) {
      return;
    }

    try {
      const token = localStorage.getItem('token');
      const response = await fetch(getApiUrl('api/whatsapp/disconnect'), {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${token}`
        }
      });

      if (response.ok) {
        setWhatsappConnected(false);
        setConnectionDetails(null);
        setQrCodeData(null);
        alert('WhatsApp disconnected successfully');
      } else {
        const data = await response.json();
        alert(data.message || 'Failed to disconnect WhatsApp');
      }
    } catch (error) {
      console.error('Disconnect error:', error);
      alert('Failed to disconnect WhatsApp');
    }
  };

  return (
    <div className="flex-1 p-4 md:p-6 lg:p-8">
      <h1 className="text-[#2D3748] mb-6">Link Accounts</h1>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4 md:gap-6">
        {/* Email Configuration Card */}
        <div className="bg-white rounded-lg shadow-sm p-4 md:p-6">
          <div className="flex items-center gap-3 mb-4">
            <div className="w-12 h-12 bg-[#008080]/10 rounded-lg flex items-center justify-center">
              <Mail className="w-6 h-6 text-[#008080]" />
            </div>
            <div className="flex-1">
              <h2 className="text-[#2D3748]">Email Sending Configuration</h2>
              <div className="flex items-center gap-2 mt-1">
                {emailConnected ? (
                  <>
                    <CheckCircle2 className="w-4 h-4 text-green-600" />
                    <span className="text-sm text-green-600">Connected</span>
                  </>
                ) : (
                  <>
                    <XCircle className="w-4 h-4 text-[#718096]" />
                    <span className="text-sm text-[#718096]">Disconnected</span>
                  </>
                )}
              </div>
            </div>
          </div>

          <div className="space-y-4 mb-6">
            <div>
              <label className="block text-sm text-[#718096] mb-2">SMTP Host</label>
              <input
                type="text"
                value={smtpHost}
                onChange={(e) => setSmtpHost(e.target.value)}
                placeholder="smtp.gmail.com"
                className="w-full px-4 py-2 border border-[#718096]/30 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#008080] focus:border-transparent"
              />
            </div>
            <div>
              <label className="block text-sm text-[#718096] mb-2">SMTP Port</label>
              <input
                type="text"
                value={smtpPort}
                onChange={(e) => setSmtpPort(e.target.value)}
                placeholder="587"
                className="w-full px-4 py-2 border border-[#718096]/30 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#008080] focus:border-transparent"
              />
            </div>
            <div>
              <label className="block text-sm text-[#718096] mb-2">Username</label>
              <input
                type="text"
                value={smtpUsername}
                onChange={(e) => setSmtpUsername(e.target.value)}
                placeholder="your-email@example.com"
                className="w-full px-4 py-2 border border-[#718096]/30 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#008080] focus:border-transparent"
              />
            </div>
            <div>
              <label className="block text-sm text-[#718096] mb-2">Password</label>
              <input
                type="password"
                value={smtpPassword}
                onChange={(e) => setSmtpPassword(e.target.value)}
                placeholder="••••••••"
                className="w-full px-4 py-2 border border-[#718096]/30 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#008080] focus:border-transparent"
              />
            </div>
          </div>

          {emailConnected ? (
            <button
              onClick={handleEmailDisconnect}
              className="w-full bg-red-500 text-white px-6 py-2 rounded-lg hover:bg-red-600 transition-colors mb-4 flex items-center justify-center gap-2"
            >
              <LogOut className="w-4 h-4" />
              Disconnect
            </button>
          ) : (
            <button
              onClick={handleEmailConnect}
              className="w-full bg-[#008080] text-white px-6 py-2 rounded-lg hover:bg-[#006666] transition-colors mb-4"
            >
              Connect SMTP
            </button>
          )}

          <div className="relative mb-4">
            <div className="absolute inset-0 flex items-center">
              <div className="w-full border-t border-[#718096]/20"></div>
            </div>
            <div className="relative flex justify-center text-sm">
              <span className="px-2 bg-white text-[#718096]">Or connect with</span>
            </div>
          </div>

          <div className="grid grid-cols-2 gap-3">
            <button
              onClick={handleGoogleAuth}
              className="px-4 py-2 border border-[#718096]/30 rounded-lg hover:bg-[#F5F7F9] transition-colors text-sm text-[#2D3748]"
            >
              Gmail
            </button>
            <button
              onClick={handleOutlookAuth}
              className="px-4 py-2 border border-[#718096]/30 rounded-lg hover:bg-[#F5F7F9] transition-colors text-sm text-[#2D3748]"
            >
              Outlook
            </button>
          </div>
        </div>

        {/* WhatsApp Configuration Card */}
        <div className="bg-white rounded-lg shadow-sm p-4 md:p-6">
          <div className="flex items-center gap-3 mb-4">
            <div className="w-12 h-12 bg-green-500/10 rounded-lg flex items-center justify-center">
              <MessageCircle className="w-6 h-6 text-green-600" />
            </div>
            <div className="flex-1">
              <h2 className="text-[#2D3748]">WhatsApp Business Link</h2>
              <div className="flex items-center gap-2 mt-1">
                {whatsappConnected ? (
                  <>
                    <CheckCircle2 className="w-4 h-4 text-green-600" />
                    <span className="text-sm text-green-600">Connected</span>
                  </>
                ) : (
                  <>
                    <XCircle className="w-4 h-4 text-[#718096]" />
                    <span className="text-sm text-[#718096]">Disconnected</span>
                  </>
                )}
              </div>
            </div>
          </div>

          {whatsappConnected ? (
            // Connection Details
            <div className="bg-green-50 border border-green-200 rounded-lg p-6 mb-6">
              <h3 className="text-sm font-medium text-green-800 mb-4">Connection Details</h3>
              <div className="space-y-3">
                {connectionDetails ? (
                  <>
                    <div className="flex items-center gap-3">
                      <User className="w-5 h-5 text-green-600" />
                      <div>
                        <p className="text-xs text-green-600">Name</p>
                        <p className="text-sm font-medium text-green-800">{connectionDetails.name || 'N/A'}</p>
                      </div>
                    </div>
                    <div className="flex items-center gap-3">
                      <Phone className="w-5 h-5 text-green-600" />
                      <div>
                        <p className="text-xs text-green-600">Phone Number</p>
                        <p className="text-sm font-medium text-green-800">{connectionDetails.phoneNumber || 'N/A'}</p>
                      </div>
                    </div>
                    {connectionDetails.platform && (
                      <div className="flex items-center gap-3">
                        <MessageCircle className="w-5 h-5 text-green-600" />
                        <div>
                          <p className="text-xs text-green-600">Platform</p>
                          <p className="text-sm font-medium text-green-800 capitalize">{connectionDetails.platform}</p>
                        </div>
                      </div>
                    )}
                  </>
                ) : (
                  <p className="text-sm text-green-700">Loading connection details...</p>
                )}
                <div className="pt-3 border-t border-green-200">
                  <button
                    onClick={handleWhatsAppDisconnect}
                    className="w-full flex items-center justify-center gap-2 bg-red-600 text-white px-4 py-2 rounded-lg hover:bg-red-700 transition-colors text-sm font-medium"
                  >
                    <LogOut className="w-4 h-4" />
                    Disconnect WhatsApp
                  </button>
                </div>
              </div>
            </div>
          ) : (
            // Connection Instructions (only shown when NOT connected)
            <div className="bg-[#F5F7F9] rounded-lg p-6 mb-6">
              <h3 className="text-sm text-[#2D3748] mb-3">How to connect:</h3>
              <ol className="space-y-2 text-sm text-[#718096]">
                <li className="flex gap-2">
                  <span className="text-[#008080] flex-shrink-0">1.</span>
                  <span>Open WhatsApp Business on your phone</span>
                </li>
                <li className="flex gap-2">
                  <span className="text-[#008080] flex-shrink-0">2.</span>
                  <span>Go to Settings → Linked Devices</span>
                </li>
                <li className="flex gap-2">
                  <span className="text-[#008080] flex-shrink-0">3.</span>
                  <span>Tap "Link a Device"</span>
                </li>
                <li className="flex gap-2">
                  <span className="text-[#008080] flex-shrink-0">4.</span>
                  <span>Scan the QR code displayed below</span>
                </li>
              </ol>
            </div>
          )}

          {!whatsappConnected && (
            <div className="bg-white border-2 border-dashed border-[#718096]/30 rounded-lg p-8 mb-6 flex items-center justify-center min-h-[300px]">
              {qrCodeLoading ? (
              <div className="text-center">
                <div className="w-12 h-12 border-4 border-green-600 border-t-transparent rounded-full animate-spin mx-auto mb-3"></div>
                <p className="text-sm text-[#718096]">Generating QR Code...</p>
              </div>
            ) : qrCodeData && !qrCodeExpired ? (
              <div className="text-center">
                {qrCodeData.qrCodeImage ? (
                  // Display QR code as image if available
                  <div className="bg-white p-4 rounded-lg inline-block mb-4 shadow-sm">
                    <img 
                      src={qrCodeData.qrCodeImage} 
                      alt="WhatsApp QR Code" 
                      className="w-64 h-64 mx-auto"
                    />
                  </div>
                ) : (
                  // Fallback to SVG QR code generator
                  <div className="bg-white p-4 rounded-lg inline-block mb-4 shadow-sm">
                    <QRCodeSVG
                      value={qrCodeData.qrCodeUrl || qrCodeData.qrData || 'https://web.whatsapp.com'}
                      size={256}
                      level="H"
                      includeMargin={true}
                      imageSettings={{
                        src: '',
                        height: 0,
                        width: 0,
                        excavate: false,
                      }}
                    />
                  </div>
                )}
                <p className="text-sm text-[#718096] mb-2 font-medium">Scan this QR code with WhatsApp</p>
                <p className="text-xs text-[#718096]">Open WhatsApp → Settings → Linked Devices → Link a Device</p>
                {qrCodeExpired && (
                  <p className="text-xs text-red-600 mt-2">QR Code expired. Please generate a new one.</p>
                )}
              </div>
            ) : qrCodeExpired ? (
              <div className="text-center">
                <div className="w-48 h-48 bg-red-50 rounded-lg flex items-center justify-center mb-3 mx-auto">
                  <XCircle className="w-16 h-16 text-red-300" />
                </div>
                <p className="text-sm text-red-600 mb-2">QR Code Expired</p>
                <p className="text-xs text-[#718096]">Please generate a new QR code</p>
              </div>
            ) : (
              <div className="text-center">
                <div className="w-48 h-48 bg-[#F5F7F9] rounded-lg flex items-center justify-center mb-3 mx-auto">
                  <MessageCircle className="w-16 h-16 text-[#718096]/30" />
                </div>
                <p className="text-sm text-[#718096]">QR Code will appear here</p>
                <p className="text-xs text-[#718096] mt-1">Click "Generate QR Code" to start</p>
              </div>
              )}
            </div>
          )}

          {!whatsappConnected && (
            <div className="flex gap-3">
            <button
              onClick={handleWhatsAppConnect}
              disabled={qrCodeLoading}
              className="flex-1 bg-green-600 text-white px-6 py-2 rounded-lg hover:bg-green-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
            >
              {qrCodeLoading ? (
                <>
                  <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
                  <span>Generating...</span>
                </>
              ) : qrCodeData && !qrCodeExpired ? (
                <>
                  <RefreshCw className="w-4 h-4" />
                  <span>Refresh QR Code</span>
                </>
              ) : (
                <>
                  <MessageCircle className="w-4 h-4" />
                  <span>Generate QR Code</span>
                </>
              )}
            </button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

